Repository hansajayathilaka/fyp, pull requests merged in 2025-03, with the labels that each got.

#20 suppress hydration error
  front_end/public/icons/logo.png
  front_end/src/app/page.tsx
  front_end/src/components/navbar.tsx
  front_end/src/components/theme-provider.tsx
Labels: bug

#31 Nav bar mobile view development
  front_end/src/app/globals.css
  front_end/src/app/layout.tsx
  front_end/src/components/landingPage/AboutSection.tsx
  front_end/src/components/landingPage/FooterSection.tsx
  front_end/src/components/landingPage/HeroSection.tsx
  front_end/src/components/landingPage/Layout.tsx
  front_end/src/components/landingPage/WhyChooseSection.tsx
  front_end/src/components/navbar.tsx
  front_end/src/components/navbar/ConnectWalletButton.tsx
  front_end/src/components/navbar/LightDarkSwitcherButton.tsx
  front_end/src/components/navbar/MobileNavBar.tsx
  front_end/src/components/navbar/NavBarItem.tsx
  front_end/src/components/navbar/navbar.tsx
  front_end/src/data/Navbar.ts
  front_end/src/types/navBar.ts
Labels: enhancement

#30 18 footer section landing page
  front_end/src/components/footer.tsx
  front_end/src/components/landingPage/FooterSection.tsx
Labels: feature

#32 26 hero section landing page
  front_end/src/app/layout.tsx
  front_end/src/components/RegistrationButton.tsx
  front_end/src/components/landingPage/HeroSection.tsx
  front_end/src/components/landingPage/Layout.tsx
  front_end/src/components/navbar/navbar.tsx
  front_end/src/types/registrationButtonBype.ts
Labels: feature
